Desktop version review
akezeth/Portfolio-setup-and-mobile-first pull request #5
Opened 2023-03-31 11:58 UTC by akezeth

Added structure and style for the desktop version of the figma design template 2.
Used media query with min-width = 768px.
Used both Grid and Flexbox for styling the structure of the page.

2023-03-31 12:30 UTC, topeogunleye requested changes
Hi @akezeth, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

> ## (Highlights) Good Points: 💪 
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * Professional README file. :heavy_check_mark:
> * PR has a good title and summary :heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Nothing to mention.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-31 12:30 UTC, topeogunleye commented on index.html
>                  <h2 class="recentWorks">
- [ ] As written in the project requirements. I kindly suggest that you ensure that when a project is hovered on with the mouse:
-  the description and dark opacity disappear
-  and a See Project button appears to the bottom of the image and takes the whole image width.
-   Your `See Project` button should link to the Live Demo of the project or to the GitHub repository.
-   The project text should take up no more than 3 lines of text. Your project text currently takes up 4 lines of text.

| Your Design  |Template Design |
| ------------- | ------------- |
| <img width="865" alt="image" src="https://user-images.githubusercontent.com/52934128/229117140-1fb183e2-e817-4896-bfdf-5726c602a85f.png"> | ![image](https://user-images.githubusercontent.com/52934128/178112550-f1b33dc5-838e-4251-898a-ea299dc20431.png) |

2023-03-31 18:21 UTC, akezeth commented
Added hover state property for the work div elements.
Added link for See Project button.

2023-03-31 19:09 UTC, Zuhaib042 requested changes
Hi @akezeth , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![](https://media.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif)

 ## Highlights
Followed Github flow ✔️
Professional README file. ✔️
PR has a good title and summary ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-31 19:09 UTC, Zuhaib042 commented on index.html
>                  <h2 class="recentWorks">
- [ ] What the previous reviewer meant here was the following:- 
  -  First, without hovering the mouse on the card, the `see button` should not be there. 
  -  Then, when hovering the mouse on card, the description and dark opacity should disappear and `see button` shows up. you can achieve this by using `:hover` pseudoclass, and not with the click.
Right now, the hover effect is not working on these cards. I had to click, and even on clicking, the desired effect is not there.
 your design now.

https://user-images.githubusercontent.com/96683843/229208198-c4b7b2f1-c3ff-4151-b7af-44e044e36299.mov

2023-04-01 02:24 UTC, topeogunleye commented
> Added hover state property for the work div elements. Added link for See Project button.



> Added hover state property for the work div elements. Added link for See Project button.

@akezeth Here's of video demo of the Expected App behavior:

https://www.loom.com/share/66329832a272445b989fa32dac2e5796

2023-04-01 05:39 UTC, akezeth commented
Modified hover state property for the work div elements.

2023-04-01 05:55 UTC, TadesseDev approved these changes
### Hi @akezeth 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy (1)](https://user-images.githubusercontent.com/69077061/212969210-69f495ba-f2fb-4559-a222-d1507310d6fb.gif)



## Highlights
 - [x] Good job making the changes requested by the previous code reviewer. ✅
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-01 06:10 UTC, merged